title: Portfolio
name: Chang-ill
email: bchi2000@gmail.com
description: >-
  안녕하십니까. <br>개발자를 꿈꾸는 변창일입니다.</br>


baseurl: ""
url: "https://BYUNCHANGILL.github.io/portfolio"


# profile 이미지
profile_image: images/about.jpg


# SNS 아이디
# # facebook_id: https://github.com/BYUNCHANGILL
# instagram_id: babycheetah
github_id: BYUNCHANGILL


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2

# slider type 0  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/cover_bg_1.jpg
  title: I am<br>Developer
  subtitle: >- 
    조금은 늦었지만<br>
    아무것도 몰랐지만<br>
    무작정 따라하며 성장해온<br>
    초보 개발자 변창일입니다.
  position: absolute
  transform: translate(-50%, -50%)
  left: 200px
  bottom: 200px  

# About
about_meta: About Me
about_header: >- 
  코딩이 무엇인지도 모르고 도전한 "나"
about_introduce: >-
  "안녕하세요. 풀스택 전문가를 꿈꾸는 초보 개발자입니다."
about_content: >-
  평소 여가 시간에 컴퓨터나 휴대폰으로 여러 콘텐츠를 둘러보던 중 <br>
  문득 제가 구축한 서비스를 사람들이 편리하게 이용한다면 스스로 큰 보람을 느낄 것 같다는 생각을 했습니다. <br>
  무언가를 새로 시작하기엔 다소 늦은 나이라는 주위의 만류에도 <br>
  저는 다니던 직장을 관두고 학원을 다니기 시작했습니다. <br>
  아무것도 모르고 너무나 부족함을 알았기에 모든것을 따라했습니다. <br>
  <strong>전공자도 아니였고 아직도 모르는것 투성이지만 조금 늦은만큼 더 열심히 배워가고 있습니다.</strong>

about_services: # 형식에 맞추어 항목 추가
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-code
  name: Java Script
- icon: icon-code
  name: Spring Boot
  # 신념 혹은 자우명
about_box_content: 
  즐기는 사람을 이길 자는 없습니다. <br><br>
  하지만 그 누구도 수십년을 꾸준히 해온 <br><br>
  <b>'장인'</b>은 이길 수 없습니다.
about_box_button:
  link: https://github.com/BYUNCHANGILL
  name: 이 구역의 '장인'은 제가 되겠습니다.


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: #
tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-1
  animation: fadeInLeft
  percent: #
  mark: #
  content: 자바 기초, 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.
- name: MariaDB
  color: color-2
  animation: fadeInRight
  percent: #
  mark: #
  content: 공부하면 공부할수록 이 분야가 정말 방대하고 제가 아는것이 정말 일부분이라는 것을 많이 느낍니다. 기초 이론부터 다시 배우겠다는 마음으로 공부하고 있습니다.
- name: JS
  color: color-3
  animation: fadeInLeft
  percent: #
  mark: #
  content: JavaScript를 활용하며, 팀 프로젝트를 해보았습니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: #
  mark: #
  content: 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리합니다.
- name: Spring Boot
  color: color-5
  animation: fadeInLeft
  percent: #
  mark: #
  content: 팀 프로젝트를 Spring Boot 로 만들었습니다.  
tech_desc: 앞으로도 여기에 그치지 않고 <strong>다른 언어 및 기술</strong>등을 계속해서 조금씩 공부할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 저의 Project 를 소개합니다.
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: https://github.com/BYUNCHANGILL

# project_my_name: 개인프로젝트

# project_my: # 형식에 맞추어 항목 추가
# - background_url: images/personal_project1.PNG
#   animation: fadeInLeft
#   name: 딥러닝 불량품 검출(2021.04)
#   description: 실패한 공모전을 대학원 기말 프로젝트를 통해 몰랐던부분을 배우고 해결하였습니다. 공장에서 만들어내는 부품의 데이터를 통해 불량품을 검출하는 프로젝트입니다. 
#   detail_url: #
#   readmore_url: #

# - background_url: images/blog-1.PNG
#   animation: fadeInLeft
#   name: 개인 프로젝트 어쩌구
#   description: 설명설명 설명 설명
#   detail_url: #
#   readmore_url: #

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/localhost.png
  animation: fadeInRight
  name: 오늘 뭐먹지?(2022.03)
  description: 남녀노소 누구나 고민거리인 오늘 뭐먹지... 현 위치 기반으로 음식 및 식당을 추천해주는 웹 사이트를 개발하였습니다.
  detail_url: pdf/project.pdf
  readmore_url: https://github.com/TeamGSVL/o_neul_final

# Experience
exp_meta: What have I achieved?
exp_header: 저는 팀 프로젝트 진행동안 이런 '경험'을 했습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 소통
  color: color-1
  icon: icon-bulb
  content: 프로젝트 진행 동안 상시 소통을 통해 서로 다양한 의견을 주고받고 원활한 진행을 할 수 있었습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 프로젝트를 기획, 진행 해왔기에 업무에 대한 협력과 배분이 익숙합니다. 새로운 프로젝트에 도전적입니다.
# exp_counters:
# - name: Online Class Sales
#   count: 344
#   speed: 10000
# - name: project
#   count: 6
#   speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 코리아와이드아이티에스
  date: 2020.06~2021.07
  content: 버스, 버스정류장 유지보수
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft
- name: 제일메디칼
  date: 2018.10~2020.06
  content: 제품 재고 관리
  color: color-2
  icon: icon-pen2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Daegu Gacholic University
  subtitle: 대구 가톨릭 대학교
  date: 2009.03 - 2018.08
  content: #
- title: Ohseong High School
  subtitle: 오성고등학교
  date: 2006.03 - 2008.02
  content: #


# Blog
blog_meta: self-improvement
blog_header: BLOG and YOUTUBE
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: #
blog_list:
- title: 아기치타의 AI 대학원 블로그
  subtitle: 개발 블로그 운영
  date: 2021.01
  content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
  thumbnail_url: images/blog-1.PNG
  link: #
- title: 따라쟁이의 유튜브
  subtitle: 개발,논문 유튜브 채널 운영
  date: 2018.04
  content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
  thumbnail_url: images/blog-2.PNG
  link: #
- title: 네이버블로그
  subtitle: 이전 블로그
  date: 2018.03
  content: 막 복학을하고 전과했을때 시작했던 첫블로그입니다.
  thumbnail_url: images/blog-3.PNG
  link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: 이런것들도 손쉽게 고칠수 있게 만들어주세요
  icon: icon-globe-outline
- title: 주소
  icon: icon-map
- title: +82 10 xxxx xxxx
  icon: icon-phone
- title: 웹 주소
  icon: icon-layers2
  url: https://google.com
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
